language: go

go:
  - "1.10"

addons:
  sonarcloud:
    organization: "agigleux-github"
    token:
      secure: ""
      
install:
  # Installs Go Meta Linter (Golint and Go vet are also supported independently)
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - $GOPATH/bin/gometalinter.v2 --install

script:
  # Execute Go Meta Linter
  - $GOPATH/bin/gometalinter.v2 samples/ > gometalinter-report.out || true
  # Execute tests
  - go test -json | sed 's|github.com/SonarSource/sonarcloud_example_go-sqscanner-travis|samples|g' > report.json
  # And then execute SonarCloud analysis which will run its own code analysis, and also reuse the linters' results
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
